### ISSUE TITLE
Milestone meeting notes

### ISSUE THREAD

**Issue by strogonoff** [isogr/register-system-transition#34]
- [ ] Can we replace production with a static snapshot now?
- [ ] How close does end-user site need to be to 2013 GR system in order to be production-ready?
- [ ] Can we use isogr.org domain for the register? (Production or staging?)
- [ ] Approaches to deploying a staging instance. Can we have 1 global staging instance with CB pending proposals? Can we dynamically generate per-proposal staging domains (or subpaths)?
- [ ] Searching by extent boundaries (general question)
